config/routes.rb
Rails.application.routes.draw do
  get 'about', controller: :static, action: :about, alias: 'about'

  get 'services', controller: :static, action: :services, alias: 'services'

  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  layout 'static'
  def about
  end

  def services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<p>Welcome to the layout Application</p>

app/views/layouts/_menu.html.erb
<ul>
    <li style="display: inline"><%= link_to 'Home', root_path %></li>
    <li style="display: inline"><%= link_to 'About Us', about_path %></li>
    <li style="display: inline"><%= link_to 'Our Services', services_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Layoutsapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/menu' %>
<%= yield %>

</body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Layoutsapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/menu' %>
  <%= yield :intro %>
  <%= yield %>

</body>
</html>